"""Example: ASR-validate every ``--long`` chunk with mlx-whisper + a word-error-rate gate.

``generate_long``'s built-in ``chunk_health`` guard is cheap and dependency-free, so it
only catches *degenerate* audio — silence, non-finite samples, or a clip far too short for
its text. It cannot catch a **same-length hallucination**: a chunk that is the right
length and sounds fine but says the wrong words. Catching that needs a transcript, which
means an ASR dependency — so the package and the CLI deliberately stay dependency-free and
expose the hook instead: ``generate_long(validator=…)``.

This script is the reference implementation of that hook. It transcribes each candidate
chunk with `mlx-whisper <https://github.com/ml-explore/mlx-examples/tree/main/whisper>`_,
computes a plain word error rate against the text that chunk was *supposed* to say, and
accepts the chunk when ``WER <= --max-wer``. A rejected chunk is regenerated by
``generate_long`` with a fresh seed, up to ``--max-retries`` times — the retry/reseed loop
already lives in the library, so the validator only has to answer accept-or-reject.

WER (not word *coverage*) is the metric here because coverage is recall-only: a
hallucinated clip that says every intended word plus a sentence of invented text scores
perfect coverage. WER counts insertions and substitutions too, which is exactly the
failure mode the hook exists for. (``scripts/gate_generate_long_retry.py`` is the
maintainer's on-device acceptance gate for the retry machinery and uses a coverage
validator; this is the general-purpose, copy-me version.)

**Whitespace-delimited languages only.** The WER here tokenizes on ``\\w+``, which is
unicode-aware but still whitespace-delimited in effect: a script written *without* spaces
(Chinese, Japanese, Thai, Lao, Khmer, Burmese) collapses a whole clause into a single
token, so the word error rate can only come out 0.0 or 1.0 and the gate carries no
information. Rather than score those wrongly, the script detects them up front and exits.
dots.tts itself renders them fine — it is this example's metric that does not apply.
Scoring them properly needs language-aware segmentation (jieba, MeCab, PyThaiNLP, …),
which is out of scope for a copy-me example; swap ``normalize_words`` if you need it.

Requires ``mlx-whisper`` — NOT a dependency of this package. Install it alongside:

    pip install mlx-whisper

Run:

    python examples/asr_validated_long.py \
        --model weights/dots_tts_mlx \
        --text "First sentence. Second sentence. Third one here." \
        --ref-audio reference.wav --ref-text "transcript of reference.wav" \
        --language EN --out outputs/asr_validated.wav

The first run downloads the Whisper weights named by ``--whisper``. Pick a smaller repo
(e.g. ``mlx-community/whisper-tiny``) for a quick smoke test; validation quality tracks
the ASR model, and a weak ASR will reject good audio.
"""
from __future__ import annotations

import argparse
import math
import os
import re

import mlx.core as mx
import numpy as np
import soundfile as sf

# Whisper consumes 16 kHz mono; dots.tts emits 48 kHz.
_ASR_SAMPLE_RATE = 16000
_WORD_RE = re.compile(r"\w+", re.UNICODE)

# Scripts conventionally written WITHOUT spaces between words. `\w+` cannot segment
# these, so the WER gate below does not apply to them -- see `unscorable_script`.
_NO_SPACE_SCRIPT_RE = re.compile(
    "["
    "\u3040-\u30ff"  # Hiragana + Katakana
    "\u3400-\u4dbf"  # CJK Unified Ideographs Extension A
    "\u4e00-\u9fff"  # CJK Unified Ideographs
    "\uf900-\ufaff"  # CJK Compatibility Ideographs
    "\u0e00-\u0e7f"  # Thai
    "\u0e80-\u0eff"  # Lao
    "\u1000-\u109f"  # Myanmar
    "\u1780-\u17ff"  # Khmer
    "]"
)


def resample_mono(
    x: np.ndarray, orig_freq: int, new_freq: int, *, half_width: int = 16
) -> np.ndarray:
    """Windowed-sinc resample of a 1-D signal (Hann window, 0.95 x lower-Nyquist cutoff).

    Deliberately self-contained: dots-tts-mlx's own resampler is private because it
    mirrors torchaudio bit-for-bit to hold the conversion parity gates, and an example
    should not reach into a library's internals for something this small. Feeding Whisper
    is not a parity-critical path -- this is well past good enough for it, and any DSP
    library (``scipy.signal.resample_poly``, ``torchaudio.functional.resample``,
    ``librosa.resample``) is a drop-in replacement if you already have one installed.
    """
    x = np.asarray(x, dtype=np.float32).ravel()
    if orig_freq == new_freq or x.size == 0:
        return x
    ratio = float(new_freq) / float(orig_freq)
    cutoff = 0.95 * min(1.0, ratio)  # anti-alias below the LOWER of the two Nyquists
    taps = math.ceil(half_width / cutoff)
    offsets = np.arange(-taps + 1, taps + 1)
    padded = np.pad(x, (taps, taps))
    n_out = math.floor(x.size * ratio)
    out = np.empty(n_out, dtype=np.float32)

    # Blocked so the [n_out, 2*taps] gather stays bounded regardless of clip length.
    for start in range(0, n_out, 4096):
        stop = min(start + 4096, n_out)
        positions = np.arange(start, stop, dtype=np.float64) / ratio
        base = np.floor(positions).astype(np.int64)
        delta = (positions[:, None] - (base[:, None] + offsets[None, :])) * cutoff
        window = np.where(
            np.abs(delta) < half_width, 0.5 * (1.0 + np.cos(np.pi * delta / half_width)), 0.0
        )
        kernel = np.sinc(delta) * window * cutoff
        taken = padded[base[:, None] + offsets[None, :] + taps]
        out[start:stop] = (taken * kernel).sum(axis=1).astype(np.float32)
    return out


def normalize_words(text: str) -> list[str]:
    """Lowercase + strip punctuation -> word list. Whitespace-delimited scripts only."""
    return _WORD_RE.findall((text or "").lower())


def unscorable_script(text: str) -> str | None:
    """Return a reason string when the WER gate cannot meaningfully score ``text``.

    ``normalize_words`` splits on ``\\w+``. That is unicode-aware, but it is *not*
    script-agnostic: in a language written without spaces, one ``\\w+`` match swallows an
    entire clause, so the reference and the hypothesis are each a single "word" and WER
    degenerates to 0.0 (byte-identical) or 1.0 (anything else) -- no gradient, no useful
    threshold.

    The check is presence-based rather than "the whole string has no spaces": one embedded
    CJK clause inside otherwise-spaced text is already enough to make the number wrong, and
    an example should refuse rather than report a confidently meaningless WER.
    """
    hits = sorted(set(_NO_SPACE_SCRIPT_RE.findall(text or "")))
    if not hits:
        return None
    sample = "".join(hits[:8])
    return (
        "this example's WER gate only works for whitespace-delimited languages, and "
        f"--text contains characters from a script written without spaces ({sample}...). "
        "`\\w+` collapses such a clause into a single token, so the word error rate can "
        "only be 0.0 or 1.0 and the gate would carry no information. dots.tts renders "
        "these languages fine -- it is this validator that does not apply. To gate them, "
        "replace normalize_words() with a language-aware segmenter (jieba / MeCab / "
        "PyThaiNLP) and rerun."
    )


def word_error_rate(reference: str, hypothesis: str) -> float:
    """Standard WER = (substitutions + deletions + insertions) / len(reference words).

    Levenshtein over word lists. Returns 0.0 when both sides are empty and 1.0 when only
    the reference is empty but something was heard (i.e. pure insertion).
    """
    ref, hyp = normalize_words(reference), normalize_words(hypothesis)
    if not ref:
        return 0.0 if not hyp else 1.0
    # Two-row dynamic program; row[j] = edit distance between ref[:i] and hyp[:j].
    previous = list(range(len(hyp) + 1))
    for i, r in enumerate(ref, start=1):
        current = [i]
        for j, h in enumerate(hyp, start=1):
            current.append(
                previous[j - 1] if r == h else 1 + min(previous[j - 1], previous[j], current[j - 1])
            )
        previous = current
    return previous[-1] / len(ref)


class WhisperWerValidator:
    """``validator(audio, chunk_text, sample_rate) -> WER(chunk_text, ASR(audio)) <= threshold``.

    Matches the callback signature ``generate_long(validator=…)`` expects. Transcribes the
    candidate in memory (no temp wav, no ffmpeg) and records every decision on ``.calls``
    so the caller can report on what happened.
    """

    def __init__(self, whisper_repo: str, *, threshold: float = 0.5, language: str | None = None):
        if float(threshold) < 0.0:
            raise ValueError(f"threshold must be >= 0 (got {threshold}); see --max-wer.")
        self.whisper_repo = whisper_repo
        self.threshold = float(threshold)
        # dots.tts takes an uppercase ISO code ("EN"); whisper wants lowercase ("en").
        self.language = language.lower() if language else None
        self.calls: list[dict] = []

    def transcribe(self, audio: np.ndarray, sample_rate: int) -> str:
        # Imported lazily so this module stays importable (and unit-testable) without
        # mlx-whisper installed.
        try:
            import mlx_whisper
        except ImportError as exc:  # pragma: no cover - depends on the user's env
            raise SystemExit(
                "this example needs mlx-whisper, which is not a dependency of "
                "dots-tts-mlx. Install it with:  pip install mlx-whisper"
            ) from exc

        audio = np.asarray(audio, dtype=np.float32).ravel()
        audio16k = resample_mono(audio, int(sample_rate), _ASR_SAMPLE_RATE)
        result = mlx_whisper.transcribe(
            audio16k, path_or_hf_repo=self.whisper_repo, language=self.language
        )
        return str(result.get("text", "")).strip()

    def __call__(self, audio: np.ndarray, chunk_text: str, sample_rate: int) -> bool:
        transcript = self.transcribe(audio, sample_rate)
        wer = word_error_rate(chunk_text, transcript)
        accepted = wer <= self.threshold
        self.calls.append(
            {"chunk": chunk_text, "transcript": transcript, "wer": wer, "accepted": accepted}
        )
        print(
            f"  [asr] WER {wer:.2f} {'ok' if accepted else 'REJECT'}  "
            f"want: {chunk_text!r}\n        heard: {transcript!r}",
            flush=True,
        )
        return accepted


def wer_threshold(value: str) -> float:
    """``--max-wer`` parser: reject a negative rate, allow one above 1.0 on purpose.

    WER has no upper bound — the edit distance is divided by the *reference* length, so
    insertions can push it past 1.0 (a chunk that says the right words plus a fabricated
    sentence scores well over 1). A threshold above 1.0 is therefore a meaningful, if
    lax, setting: it still rejects catastrophic hallucination while tolerating a lot of
    padding. It is left uncapped rather than clamped so that a caller who deliberately
    wants that gets it, instead of a silently different gate. A *negative* threshold, by
    contrast, can never be satisfied — it would reject every chunk and burn the full
    retry budget on each — so it is rejected outright.
    """
    rate = float(value)
    if rate < 0.0:
        raise argparse.ArgumentTypeError(
            f"--max-wer must be >= 0 (got {rate}); a negative rate rejects every chunk. "
            "0.0 demands an exact transcript match; values above 1.0 are allowed and "
            "only reject heavy hallucination (insertions can push WER past 1)."
        )
    return rate


def build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--model", default="weights/dots_tts_mlx")
    ap.add_argument("--text", required=True)
    ap.add_argument("--ref-audio", required=True)
    ap.add_argument("--ref-text", required=True, help="exact transcript of --ref-audio.")
    ap.add_argument("--language", default=None, help="uppercase ISO code (EN/DE/HI/…).")
    ap.add_argument("--out", default="outputs/dots_tts/asr_validated.wav")
    ap.add_argument(
        "--whisper",
        default="mlx-community/whisper-large-v3-turbo",
        help="HF repo id or local path of the mlx-whisper model used to validate.",
    )
    ap.add_argument(
        "--max-wer",
        type=wer_threshold,
        default=0.5,
        help="accept a chunk when its word error rate is <= this (default 0.5). Lower is "
        "stricter; too strict and healthy audio gets regenerated for nothing. Must be "
        ">= 0; values above 1.0 are allowed deliberately, since insertions can push WER "
        "past 1.",
    )
    ap.add_argument(
        "--max-retries",
        type=int,
        default=2,
        help="reseed-retries per rejected chunk, passed to generate_long (default 2).",
    )
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--num-steps", type=int, default=None)
    ap.add_argument("--gap-ms", type=int, default=80)
    return ap


def main() -> int:
    args = build_parser().parse_args()

    reason = unscorable_script(args.text)
    if reason is not None:
        raise SystemExit(reason)

    from dots_tts_mlx.loader import from_pretrained

    model = from_pretrained(args.model, dtype=mx.bfloat16).model
    validator = WhisperWerValidator(
        args.whisper, threshold=args.max_wer, language=args.language
    )

    out = model.generate_long(
        text=args.text,
        prompt_audio=args.ref_audio,
        prompt_text=args.ref_text,
        language=args.language,
        seed=args.seed,
        num_steps=args.num_steps,
        gap_ms=args.gap_ms,
        validator=validator,
        max_retries=args.max_retries,
    )

    wav = np.asarray(out["audio"].astype(mx.float32)).ravel()
    sample_rate = int(out["sample_rate"])
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    sf.write(args.out, wav, sample_rate)

    rejected = sum(1 for c in validator.calls if not c["accepted"])
    print(
        f"\n[dots] -> {args.out}  {wav.shape[-1] / sample_rate:.2f}s  "
        f"{out['num_chunks']} chunks, {out['retries']} retries "
        f"({rejected} ASR rejections, {out['unrecovered']} still failing at the retry cap)",
        flush=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
